[phases.setup]
nixpkgsArchive = '51ad838b03a05b1de6f9f2a0fffecee64a9788ee'
aptPkgs = ['openssl']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npx prisma migrate deploy && node scripts/migrate-to-multitenant.js && node scripts/apply-tenant-constraints.js && node scripts/seed-admin.js && npm run start'